"""Statistics: bootstrap CIs, the no-signal permutation test, and multiplicity control.

These implement the pre-registration commitments of §6:
  * 95% bootstrap confidence intervals on every capacity estimate;
  * a permutation test of the null "intended and recovered bits are independent"
    (capacity = 0) — the formal basis for the benign-vs-instructed discrimination
    of §7.3;
  * Benjamini-Hochberg / Bonferroni correction across the pre-registered grid.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from .capacity import estimate_capacity
from .types import Bits


@dataclass
class CI:
    point: float
    lo: float
    hi: float
    alpha: float = 0.05

    def as_tuple(self) -> tuple[float, float, float]:
        return self.point, self.lo, self.hi


def bootstrap_capacity_ci(
    intended: list[Bits],
    decoded: list[Bits],
    n_boot: int = 1000,
    alpha: float = 0.05,
    seed: int = 0,
    **est_kwargs,
) -> CI:
    """Percentile bootstrap CI for Ĉ_ctrl by resampling trials with replacement."""
    n = len(intended)
    point = estimate_capacity(intended, decoded, **est_kwargs).capacity_bits
    if n == 0:
        return CI(point, 0.0, 0.0, alpha)
    rng = np.random.default_rng(seed)
    idx = np.arange(n)
    boots = np.empty(n_boot, dtype=float)
    for b in range(n_boot):
        take = rng.choice(idx, size=n, replace=True)
        bi = [intended[i] for i in take]
        bd = [decoded[i] for i in take]
        boots[b] = estimate_capacity(bi, bd, **est_kwargs).capacity_bits
    lo = float(np.quantile(boots, alpha / 2))
    hi = float(np.quantile(boots, 1 - alpha / 2))
    return CI(point, lo, hi, alpha)


def permutation_pvalue(
    intended: list[Bits],
    decoded: list[Bits],
    n_perm: int = 1000,
    seed: int = 0,
    **est_kwargs,
) -> float:
    """One-sided p-value for H0: capacity = 0 (intended ⟂ recovered).

    The null distribution is generated by permuting decoded rows against intended,
    destroying any association while preserving each side's marginal structure.
    """
    n = len(intended)
    if n < 2:
        return 1.0
    # Use the RAW plug-in MI as the test statistic, not the clipped/MM capacity:
    # the plug-in's positive bias cancels between the observed value and the
    # permutation null (both share it), giving a well-calibrated test. Clipping at
    # zero would collapse the null's resolution and inflate false positives.
    obs = estimate_capacity(intended, decoded, **est_kwargs).capacity_bits_raw
    rng = np.random.default_rng(seed)
    ge = 0
    for _ in range(n_perm):
        perm = rng.permutation(n)
        shuffled = [decoded[i] for i in perm]
        cap = estimate_capacity(intended, shuffled, **est_kwargs).capacity_bits_raw
        if cap >= obs - 1e-12:
            ge += 1
    return (1 + ge) / (1 + n_perm)


def benjamini_hochberg(pvals: list[float], alpha: float = 0.05) -> tuple[np.ndarray, np.ndarray]:
    """Benjamini-Hochberg FDR control.

    Returns ``(rejected, qvalues)`` aligned to the input order.
    """
    p = np.asarray(pvals, dtype=float)
    m = len(p)
    if m == 0:
        return np.array([], dtype=bool), np.array([], dtype=float)
    order = np.argsort(p)
    ranked = p[order]
    q = ranked * m / (np.arange(1, m + 1))
    # enforce monotonicity of q-values
    q = np.minimum.accumulate(q[::-1])[::-1]
    q = np.clip(q, 0, 1)
    rejected_sorted = ranked <= (np.arange(1, m + 1) / m) * alpha
    if rejected_sorted.any():
        kmax = np.max(np.where(rejected_sorted)[0])
        thresh = ranked[kmax]
    else:
        thresh = -1.0
    rejected = p <= thresh
    qvalues = np.empty(m, dtype=float)
    qvalues[order] = q
    return rejected, qvalues


def bonferroni(pvals: list[float], alpha: float = 0.05) -> tuple[np.ndarray, np.ndarray]:
    """Bonferroni FWER control. Returns ``(rejected, adjusted_p)``."""
    p = np.asarray(pvals, dtype=float)
    m = len(p)
    if m == 0:
        return np.array([], dtype=bool), np.array([], dtype=float)
    adj = np.clip(p * m, 0, 1)
    return adj <= alpha, adj


def holm_bonferroni(pvals: list[float], alpha: float = 0.05) -> tuple[np.ndarray, np.ndarray]:
    """Holm-Bonferroni step-down FWER control (the pre-registered §7 procedure).

    Returns ``(rejected, adjusted_p)`` aligned to the input order. Less conservative
    than plain Bonferroni while still controlling the family-wise error rate.
    """
    p = np.asarray(pvals, dtype=float)
    m = len(p)
    if m == 0:
        return np.array([], dtype=bool), np.array([], dtype=float)
    order = np.argsort(p)
    ranked = p[order]
    adj_sorted = np.empty(m, dtype=float)
    running = 0.0
    for i in range(m):
        running = max(running, (m - i) * ranked[i])
        adj_sorted[i] = min(running, 1.0)
    # step-down: reject until the first non-rejection
    rejected_sorted = np.zeros(m, dtype=bool)
    for i in range(m):
        if ranked[i] * (m - i) <= alpha:
            rejected_sorted[i] = True
        else:
            break
    rejected = np.zeros(m, dtype=bool)
    adjusted = np.empty(m, dtype=float)
    rejected[order] = rejected_sorted
    adjusted[order] = adj_sorted
    return rejected, adjusted


def jonckheere_terpstra(groups: list[np.ndarray], alternative: str = "increasing") -> tuple[float, float, float]:
    """Jonckheere-Terpstra ordered-trend test (H3: capacity non-decreasing in scale).

    ``groups`` are sample arrays in the hypothesized order (e.g. 8B, 14B, 32B).
    Returns ``(J, z, p_one_sided)`` using the large-sample normal approximation.
    """
    groups = [np.asarray(g, dtype=float) for g in groups if len(g) > 0]
    k = len(groups)
    if k < 2:
        return 0.0, 0.0, 1.0
    J = 0.0
    for i in range(k):
        for j in range(i + 1, k):
            gi, gj = groups[i], groups[j]
            for x in gi:
                J += np.sum(gj > x) + 0.5 * np.sum(gj == x)
    ns = np.array([len(g) for g in groups], dtype=float)
    N = ns.sum()
    mu = (N ** 2 - np.sum(ns ** 2)) / 4.0
    var = (N ** 2 * (2 * N + 3) - np.sum(ns ** 2 * (2 * ns + 3))) / 72.0
    if var <= 0:
        return float(J), 0.0, 1.0
    z = (J - mu) / np.sqrt(var)
    from scipy.stats import norm
    if alternative == "increasing":
        p = float(norm.sf(z))
    elif alternative == "decreasing":
        p = float(norm.cdf(z))
    else:
        p = float(2 * norm.sf(abs(z)))
    return float(J), float(z), p


def two_sample_bootstrap_diff(
    a_vals: np.ndarray, b_vals: np.ndarray, n_boot: int = 10000, alpha: float = 0.05, seed: int = 0,
) -> tuple[float, float, float]:
    """Bootstrap CI for mean(a) - mean(b) (used for the H2 think-toggle delta)."""
    a, b = np.asarray(a_vals, dtype=float), np.asarray(b_vals, dtype=float)
    if len(a) == 0 or len(b) == 0:
        return 0.0, 0.0, 0.0
    rng = np.random.default_rng(seed)
    diffs = (a[rng.integers(0, len(a), size=(n_boot, len(a)))].mean(axis=1)
             - b[rng.integers(0, len(b), size=(n_boot, len(b)))].mean(axis=1))
    return float(a.mean() - b.mean()), float(np.quantile(diffs, alpha / 2)), float(np.quantile(diffs, 1 - alpha / 2))
